name: MinecraftManhunt
main: com.abstractionalpha.minecraft.plugin.minecraft_manhunt.MinecraftManhunt
version: 0.1.6
api-version: 1.17
commands:
  manhunt:
    description: Access the Manhunt GUI.
    usage: /<command>
    permission: manhunt.main